"""create milestone 2 schema

Revision ID: 20260723_0001
Revises:
Create Date: 2026-07-23 21:14:08.282942
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260723_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "reporting_periods",
        sa.Column("revenue_month", sa.Date(), nullable=False),
        sa.Column("faac_meeting_date", sa.Date(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("reporting_label", sa.String(length=160), nullable=False),
        sa.Column(
            "source_status",
            sa.Enum(
                "pending",
                "registered",
                "ready_for_review",
                "approved",
                "rejected",
                "superseded",
                "demo",
                name="reporting_period_source_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (is_demo AND is_published)",
            name="ck_reporting_period_demo_not_published",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "revenue_month", "reporting_label", name="uq_reporting_period_month_label"
        ),
    )
    op.create_index(
        op.f("ix_reporting_periods_revenue_month"),
        "reporting_periods",
        ["revenue_month"],
        unique=False,
    )
    op.create_table(
        "states",
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("geopolitical_zone", sa.String(length=30), nullable=False),
        sa.Column("capital", sa.String(length=100), nullable=False),
        sa.Column("is_fct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("state_id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "source_documents",
        sa.Column("reporting_period_id", sa.Uuid(), nullable=True),
        sa.Column("source_organization", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "registered",
                "queued",
                "processing",
                "ready_for_review",
                "completed",
                "failed",
                "rejected",
                "superseded",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_status",
            sa.Enum(
                "pending",
                "registered",
                "ready_for_review",
                "approved",
                "rejected",
                "superseded",
                "demo",
                name="source_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("document_version", sa.String(length=80), nullable=False),
        sa.Column("supersedes_document_id", sa.Uuid(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(sha256) = 64", name="ck_source_document_sha256_length"
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_index(
        "ix_source_documents_publication_date",
        "source_documents",
        ["publication_date"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "canceled",
                "expired",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("plan_code", sa.String(length=80), nullable=False),
        sa.Column("external_customer_id", sa.String(length=160), nullable=True),
        sa.Column("external_subscription_id", sa.String(length=160), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_customer_id"),
        sa.UniqueConstraint("external_subscription_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_organization_id"),
        "subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "viewer",
                "analyst",
                "reviewer",
                "administrator",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=120), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "extraction_runs",
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "requires_review",
                name="extraction_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("extractor_name", sa.String(length=160), nullable=False),
        sa.Column("extractor_version", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_extracted", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_source_document_id"),
        "extraction_runs",
        ["source_document_id"],
        unique=False,
    )
    op.create_table(
        "forecasts",
        sa.Column("state_id", sa.Uuid(), nullable=True),
        sa.Column("target_period", sa.Date(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "seasonal_naive",
                "moving_average",
                "exponential_smoothing",
                name="forecast_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("point_estimate", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("lower_bound", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("upper_bound", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("training_start", sa.Date(), nullable=False),
        sa.Column("training_end", sa.Date(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="forecast_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (is_demo AND is_published)", name="ck_forecast_demo_not_published"
        ),
        sa.CheckConstraint(
            "lower_bound <= point_estimate", name="ck_forecast_lower_bound"
        ),
        sa.CheckConstraint(
            "point_estimate <= upper_bound", name="ck_forecast_upper_bound"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.state_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forecasts_state_id"), "forecasts", ["state_id"], unique=False
    )
    op.create_table(
        "generated_insights",
        sa.Column("reporting_period_id", sa.Uuid(), nullable=True),
        sa.Column("state_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("insight_type", sa.String(length=100), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("grounding", sa.JSON(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="insight_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "generated",
                "approved",
                "rejected",
                name="insight_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (is_demo AND is_published)",
            name="ck_generated_insight_demo_not_published",
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.state_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "national_distributions",
        sa.Column("reporting_period_id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column(
            "deductions_amount", sa.Numeric(precision=24, scale=2), nullable=True
        ),
        sa.Column(
            "net_distributable_amount", sa.Numeric(precision=24, scale=2), nullable=True
        ),
        sa.Column("federal_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("states_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column(
            "local_governments_amount", sa.Numeric(precision=24, scale=2), nullable=True
        ),
        sa.Column("vat_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("statutory_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column(
            "derivation_amount", sa.Numeric(precision=24, scale=2), nullable=True
        ),
        sa.Column("gross_amount_original", sa.String(length=120), nullable=True),
        sa.Column("deductions_amount_original", sa.String(length=120), nullable=True),
        sa.Column("net_amount_original", sa.String(length=120), nullable=True),
        sa.Column(
            "reported_unit",
            sa.Enum(
                "naira",
                "thousand_naira",
                "million_naira",
                "billion_naira",
                "unspecified",
                name="reported_unit",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="national_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (is_demo AND is_published)",
            name="ck_national_distribution_demo_not_published",
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporting_period_id",
            "source_document_id",
            name="uq_national_distribution_source",
        ),
    )
    op.create_index(
        op.f("ix_national_distributions_reporting_period_id"),
        "national_distributions",
        ["reporting_period_id"],
        unique=False,
    )
    op.create_table(
        "state_allocations",
        sa.Column("reporting_period_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column("gross_total", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("total_deductions", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("net_allocation", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("gross_total_original", sa.String(length=120), nullable=True),
        sa.Column("total_deductions_original", sa.String(length=120), nullable=True),
        sa.Column("net_allocation_original", sa.String(length=120), nullable=True),
        sa.Column(
            "reported_unit",
            sa.Enum(
                "naira",
                "thousand_naira",
                "million_naira",
                "billion_naira",
                "unspecified",
                name="allocation_reported_unit",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="allocation_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (is_demo AND is_published)",
            name="ck_state_allocation_demo_not_published",
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name="ck_state_allocation_confidence_range",
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.state_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporting_period_id", "state_id", name="uq_state_allocation_period_state"
        ),
    )
    op.create_index(
        op.f("ix_state_allocations_reporting_period_id"),
        "state_allocations",
        ["reporting_period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_allocations_state_id"),
        "state_allocations",
        ["state_id"],
        unique=False,
    )
    op.create_table(
        "state_indicators",
        sa.Column("reporting_period_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column("indicator_type", sa.String(length=80), nullable=False),
        sa.Column("indicator_name", sa.String(length=160), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=10), nullable=False),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="indicator_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.state_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporting_period_id",
            "state_id",
            "indicator_type",
            "indicator_name",
            name="uq_state_indicator_period_state_name",
        ),
    )
    op.create_index(
        op.f("ix_state_indicators_reporting_period_id"),
        "state_indicators",
        ["reporting_period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_indicators_state_id"),
        "state_indicators",
        ["state_id"],
        unique=False,
    )
    op.create_table(
        "state_allocation_components",
        sa.Column("state_allocation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "component_type",
            sa.Enum(
                "statutory_allocation",
                "vat",
                "derivation",
                "exchange_difference",
                "augmentation",
                "electronic_money_transfer_levy",
                "solid_minerals",
                "refunds",
                "other",
                name="component_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("component_name", sa.String(length=160), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("deduction_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("gross_amount_original", sa.String(length=120), nullable=True),
        sa.Column("deduction_amount_original", sa.String(length=120), nullable=True),
        sa.Column("net_amount_original", sa.String(length=120), nullable=True),
        sa.Column(
            "reported_unit",
            sa.Enum(
                "naira",
                "thousand_naira",
                "million_naira",
                "billion_naira",
                "unspecified",
                name="component_reported_unit",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_table", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["state_allocation_id"], ["state_allocations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_state_allocation_components_state_allocation_id"),
        "state_allocation_components",
        ["state_allocation_id"],
        unique=False,
    )
    op.create_table(
        "validation_results",
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("reporting_period_id", sa.Uuid(), nullable=True),
        sa.Column("state_allocation_id", sa.Uuid(), nullable=True),
        sa.Column("rule_code", sa.String(length=100), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "pending",
                "automatically_validated",
                "requires_review",
                "human_verified",
                "rejected",
                "superseded",
                name="validation_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "error",
                "critical",
                name="validation_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("tolerance", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "state_allocation_id IS NOT NULL OR reporting_period_id IS NOT NULL",
            name="ck_validation_result_has_subject",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"], ["extraction_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reporting_period_id"], ["reporting_periods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["state_allocation_id"], ["state_allocations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_validation_results_rule_code",
        "validation_results",
        ["rule_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_validation_results_rule_code", table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_index(
        op.f("ix_state_allocation_components_state_allocation_id"),
        table_name="state_allocation_components",
    )
    op.drop_table("state_allocation_components")
    op.drop_index(op.f("ix_state_indicators_state_id"), table_name="state_indicators")
    op.drop_index(
        op.f("ix_state_indicators_reporting_period_id"), table_name="state_indicators"
    )
    op.drop_table("state_indicators")
    op.drop_index(op.f("ix_state_allocations_state_id"), table_name="state_allocations")
    op.drop_index(
        op.f("ix_state_allocations_reporting_period_id"), table_name="state_allocations"
    )
    op.drop_table("state_allocations")
    op.drop_index(
        op.f("ix_national_distributions_reporting_period_id"),
        table_name="national_distributions",
    )
    op.drop_table("national_distributions")
    op.drop_table("generated_insights")
    op.drop_index(op.f("ix_forecasts_state_id"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(
        op.f("ix_extraction_runs_source_document_id"), table_name="extraction_runs"
    )
    op.drop_table("extraction_runs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_source_documents_publication_date", table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_table("states")
    op.drop_index(
        op.f("ix_reporting_periods_revenue_month"), table_name="reporting_periods"
    )
    op.drop_table("reporting_periods")
    op.drop_table("organizations")
    # ### end Alembic commands ###
